name: Label Sync
on:
     workflow_dispatch:
     push:
          paths:
               - '.github/labels.yml'
jobs:
     labeler:
          name: Labeler
          runs-on: ubuntu-latest
          steps:
               - name: Checkout
                 uses: actions/checkout@v3

               - name: Run
                 uses: crazy-max/ghaction-github-labeler@v4
                 with:
                      github-token: ${{ secrets.GITHUB_TOKEN }}
                      yaml-file: .github/labels.yml
                      skip-delete: false
                      dry-run: false

